# 项目配置文件， yaml 格式
server:
  port: 8080
spring:
  application:
    #应用的名称
    name: EatsRush
  shardingsphere:
    datasource:
      names: # 不固定，自定义
        master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource # 直接创建和关闭数据库连接开销很大，数据库连接池（如Druid）的作用就是预先管理一些连接，使用时从池中获取，用完后归还，从而提升性能和响应速度。
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: your_mysql_url
        username: root
        password: your_password
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: your_mysql_url
        username: root
        password: your_password
    masterslave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin #负载均衡策略：轮询
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称，主库是在这里指定的，所以上面的名称指定为什么都无所谓
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false
  main:
    allow-bean-definition-overriding: true  # 如果当前项目中存在同名的bean,后定义的bean会覆盖先定义的。如果不声明这一项，alibabaDruid和shardingJDBC中的同名bean：dataSource会冲突报错，这里让shardingJDBC覆盖alibabaDruid
  redis:
    host: xxx.xxx.xxx.xxx
    port: 6379
    password: xxxxxxxxx
    database: 0
  cache:
    redis:
      time-to-live: 1800000 # 设置缓存数据的过期时间
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志输出
  global-config:
    db-config:
      id-type: ASSIGN_ID # 插入一条新数据时，如果未主动设置主键值，自动使用雪花算法生成一个唯一的、分布式的长整型（Long）ID。
eatsRush:
  path: /user/dir # 客户端上传文件到服务器时，文件的保存路径